version: '3'
services:
  mariadb:
      build:
          context: ./docker/mariadb
      ports:
          - "3306:3306"
      volumes:
          - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./docker/mariadb/data:/var/lib/mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "no"
          MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
          MYSQL_USER: ${DATABASE_USER}
          MYSQL_PASSWORD: ${DATABASE_PASSWORD}
          MYSQL_DATABASE: ${DATABASE_NAME}
          TZ: 'America/Guatemala'
      command: mysqld --sql_mode="" --character-set-server=latin1 --collation-server=latin1_swedish_ci --innodb-flush-log-at-trx-commit=0
      restart: on-failure
  webapp:
      build:
        context: .
        dockerfile: docker/webapp/Dockerfile
      privileged: true
      ports:
          - "${HTTP_PORT}:80"
          - "${HTTPS_PORT}:443"
      volumes:
          - ./app:/var/www/html
          - ./app/vendor:/var/www/html/vendor
      links:
          - 'mariadb'
      restart: on-failure
