<?php

use Phpmig\Migration\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTableAccessByCategory extends Migration
{
    protected $table;
    protected $schema;

    public function init()
    {
        // TODO: Change the autogenerated stub
        $this->table = "wt_user_access_categories";
        $this->schema = $this->get('schema');
    }

    /**
     * Do the migration
     */
    public function up()
    {
        $this->schema->create($this->table, function(Blueprint $table){
            $table->increments("id");
            $table->integer("id_profile");
            $table->integer("id_category");
            $table->timestamps();
        });
    }

    /**
     * Undo the migration
     */
    public function down()
    {
        $this->schema->drop($this->table);
    }
}
