<?php

use Phpmig\Migration\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTableAdminNotifications extends Migration
{
    protected $table;
    protected $schema;

    public function init()
    {
        // TODO: Change the autogenerated stub
        $this->table = "wt_notification_admin";
        $this->schema = $this->get('schema');
    }

    /**
     * Do the migration
     */
    public function up()
    {
        $this->schema->create($this->table, function (Blueprint $table) {
            $table->increments("id");
            $table->string("sw_user_type", 50);
            $table->string("title", 255);
            $table->string("key_char_to_draw", 50);
            $table->longText("message");
            $table->string("url_window", 250);
            $table->string("class_style_notification");
            $table->enum("bool_filter_date", array("Y","N"))->default("N");
            $table->date("date_to");
            $table->date("date_from");
            $table->timestamps();
        });
    }

    /**
     * Undo the migration
     */
    public function down()
    {
        $this->schema->drop($this->table);
    }
}
