<?php

use Phpmig\Migration\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Capsule\Manager AS Capsule;

class AddTableToAccess extends Migration
{
    protected $tableAccess;

    public function init()
    {
        // TODO: Change the autogenerated stub
        $this->tableAccess = "wt_core_extra_access";
    }

    /**
     * Do the migration
     */
    public function up()
    {
        Capsule::schema()->create("{$this->tableAccess}", function (Blueprint $table){
            $table->increments("id");
            $table->string("module",25);
            $table->string("window",75);
            $table->string("description",250);
        });
    }

    /**
     * Undo the migration
     */
    public function down()
    {
        Capsule::schema()->drop("{$this->tableAccess}");
    }
}
