<?php

use Phpmig\Migration\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Capsule\Manager AS Capsule;

class AddTableDetailAccess extends Migration
{
    protected $tableAccessDetail;

    public function init()
    {
        // TODO: Change the autogenerated stub
        $this->tableAccessDetail = "wt_core_extra_access_detail";
    }

    /**
     * Do the migration
     */
    public function up()
    {
        Capsule::schema()->create("{$this->tableAccessDetail}", function (Blueprint $table) {
            $table->increments("id");
            $table->integer("id_user");
            $table->integer("id_profile_access");
            $table->integer("id_extra_access");
        });
    }

    /**
     * Undo the migration
     */
    public function down()
    {
        Capsule::schema()->drop("{$this->tableAccessDetail}");
    }
}