<?php

use Phpmig\Migration\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateCSVLoader extends Migration
{
	private $tableLoad = "wt_csv_load";
	private $tableProcess = "wt_csv_load_process";

	public function init()
	{
		// TODO: Change the autogenerated stub
		$this->schema = $this->get("schema");
	}

    /**
     * Do the migration
     */
    public function up()
    {
	    $this->schema->create($this->tableLoad, function(Blueprint $table){
		    $table->increments('id');
		    $table->integer("userid");
		    $table->date("date");
			$table->time("time");
			$table->string("file",255);
		    $table->enum("status", array('insert','progress','success'))->default("insert");
	    });

	    $this->schema->create($this->tableProcess, function(Blueprint $table){
		    $table->increments('id');
		    $table->string("path",255);
		    $table->string("class",50);
		    $table->string("method",50);
		    $table->enum("active", array('Y','N'))->default("Y");
		    $table->string("word_key",25);
	    });
    }

    /**
     * Undo the migration
     */
    public function down()
    {
	    $this->schema->drop($this->tableLoad);
	    $this->schema->drop($this->tableProcess);
    }
}
